ci: fail zstd installation step if zstd can't be installed
choco apparently exits 0 if it can't fetch package info:

    Failed to fetch results from V2 feed at 'https://community.chocolatey.org/api/v2/Packages(Id='zstandard',Version='1.5.7.20250308')' with following message : Response status code does not indicate success: 504 (Gateway Timeout).
    Need to add specific handling for exception type NuGetResolverInputException
    Unable to find package 'zstandard'. Existing packages must be restored before performing an install or update.

    Chocolatey installed 0/0 packages.
    See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Explicitly check that zstd was installed to avoid a confusing failure later
in the "Restore sources" step:

    Error: Failed to restore cache entry. Exiting as fail-on-cache-miss is set.

Also use `install -y` as the choco docs recommend.