qarchive: update to 2.2.1
build with C++17. It seems newer qt6 requires C++17. Errors with:

error: "Qt requires a C++17 compiler"

Signed-off-by: Rosen Penev <rosenp@gmail.com>