vo-aacenc: Add license as required by CI
AssertionError: Found files
subprojects/packagefiles/vo-aacenc/meson/makedef.py with license
headers in a project without a LICENSE.build.  The LICENSE.build file
in the patch ZIP defaults to MIT unless the patch directory has its
own LICENSE.build, which should state the license for the wrap's build
files.

The build files are MIT, but makedef.py is LGPL-2.1.