Fix using zlib.wrap with Clang on Windows (both clang and clang-cl, also ICL)
Clang is using Microsoft STL from Visual Studio on Windows, so without
this change it fails to compile the subproject with lots of issues like:

FAILED: subprojects/zlib-1.2.11/libz.a.p/gzread.c.obj
../subprojects/zlib-1.2.11/gzread.c:35:15: error: 'read' is deprecated:
The POSIX name for this item is deprecated. Instead, use the ISO C and
C++ conformant name: _read. See online help for details.
[-Werror,-Wdeprecated-declarations]