Add various self-explanatory changes
* meson: On Linux when compiling with gcc, use zlib.map

Otherwise some symbols are not visible, and as meson sets
rpath to the path of our built libz, things then fail when
for example compiling against a system-wide libpng with:

undefined reference to `gzdirect@ZLIB_1.2.2.3'

* meson: install headers and a pkg-config file
* Add windows resource file
* Add zlib.def for windows dll
* Add MSVC required defines
* Import latest LICENSE.build and readme.txt