nowide: update to 11.3.0
Fix mistake in test:

NameError: name 'stdout' is not defined

ran through pylint too.

Signed-off-by: Rosen Penev <rosenp@gmail.com>