libffi: remember to define per-target macro when generating map file
Fixes omission of FFI_GO_CLOSURES symbols from libffi on PowerPC, causing
a build failure in tests:

    ld: subprojects/libffi-3.4.6/testsuite/closure1_O2.p/libffi.go_closure1.c.o: in function `main':
    /srv/build/../subprojects/libffi-3.4.6/testsuite/libffi.go/closure1.c:21:(.text+0x7c): undefined reference to `ffi_prep_go_closure'
    ld: /srv/build/../subprojects/libffi-3.4.6/testsuite/libffi.go/closure1.c:23:(.text+0xa0): undefined reference to `ffi_call_go'